name: Second Action - Multiple Job Lineal

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Fist Step
      run: echo "Hello World"
  bye-world:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
    - name: Fist Step
      run: echo "Hello World"
    - name: Second Step
      run: echo "Bye World"
    - name: Third Step
      run: lakñdjfalñskdjf