name: Second Action - Multiple Job Lineal

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false    

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Fist Step
      run: echo "Hello World"
  bye-world:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
    - name: Fist Step
      run: echo "Hello World"
    - name: Second Step
      run: echo "Bye World"
    - name: Third Step
      run: echo "Bye World"
