name: Second Action - Multiple Job Parallel

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug mode,
        default: false
        required: false  

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Fist Step
      run: echo "Hello World"
  bye-world:
    runs-on: ubuntu-latest
    steps:
    - name: Fist Step
      run: echo "Hello World"
    - name: Second Step
      run:  echo ${{ github.event.inputs.debug_mode }}          