name: Python Tests on PR

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:
  push:
    branches:
      - '*'


jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r code/python/requirements.txt

    # Run tests
    - name: Run tests
      run: python -m unittest discover -s code/python -p "test_*.py"

    - name: Run linters
      run: |
        flake8 code/python
    
    - name: Run security checks
      run: |
        bandit -r code/python

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: code/python/DockerFile
  docker:
    runs-on: ubuntu-latest
    needs: linting
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: user/app:latest
